# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUItesting3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Main
import Predictor

class Ui_MainWindow(object):
    def runFunction(self):
        self.runStatus.setText("Status: Running")
        self.runStatus.adjustSize()

        if (not self.waterCHX.isChecked()):
            print('water ' + str(self.waterCHX.isChecked()))
            Main.mult_data.drop(Main.water, axis=1, inplace=True)
        
        if (not self.cementCHX.isChecked()):
            print('cement ' + str(self.cementCHX.isChecked()))
            Main.mult_data.drop(Main.cement, axis=1, inplace=True)
        
        if (not self.fineaggCHX.isChecked()):
            Main.mult_data.drop(Main.fine_aggr, axis=1, inplace=True)
        
        if (not self.finenessmodCHX.isChecked()):
            Main.mult_data.drop(Main.finenessmod, axis=1, inplace=True)

        if (not self.silicaCHX.isChecked()):
            Main.mult_data.drop(Main.silica, axis=1, inplace=True)

        if (not self.superplasticizerCHX.isChecked()):
            Main.mult_data.drop(Main.superplasticizer, axis=1, inplace=True)

        print(Main.mult_data)

        ann = Main.neural_network_model()
        self.trainingR2.setText("Training R<sup>2</sup> Score: " + str(ann[0]))
        self.trainingR2.adjustSize()
        self.testingR2.setText("Testing R<sup>2</sup> Score: " + str(ann[1]))
        self.testingR2.adjustSize()

        self.runStatus.setText("Status: Finished")
        self.runStatus.adjustSize()

    def predictFunction(self):
        predictedWater = self.waterplainTextEdit.toPlainText()
        predictedCement = self.cementplainTextEdit.toPlainText()
        predictedFineAggr = self.fineaggplainTextEdit.toPlainText()
        predictedFinenessMod = self.finenessmodplainTextEdit.toPlainText()
        predictedSilica = self.silicaplainTextEdit.toPlainText()
        predictedSuperplasticizer = self.superplasticizerplainTextEdit.toPlainText()

        input_predictions = [predictedWater, predictedCement, predictedFineAggr, predictedFinenessMod, predictedSilica, predictedSuperplasticizer]
        input_predictions = list(filter(None, input_predictions))
        print(input_predictions)
        for i in range(len(input_predictions)):
            input_predictions[i] = float(input_predictions[i])

        Predictor.inputprediction = [input_predictions]

        Predictor.make_prediction()
        self.compstrength.setText(self.compstrength.text() + " " + str(round(Predictor.make_prediction()[0][0],2)))
        self.compstrength.adjustSize()

        self.slump.setText(self.slump.text() + " " + str(round(Predictor.make_prediction()[0][1],2)))
        self.slump.adjustSize()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 618)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(70, 110, 71, 31))
        self.runButton.setObjectName("runButton")
        self.runButton.clicked.connect(self.runFunction)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 91, 16))
        self.label_2.setObjectName("label_2")
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setGeometry(QtCore.QRect(240, 110, 71, 31))
        self.predictButton.setObjectName("predictButton")
        self.predictButton.clicked.connect(self.predictFunction)

        self.trainingR2 = QtWidgets.QLabel(self.centralwidget)
        self.trainingR2.setGeometry(QtCore.QRect(80, 390, 251, 21))
        self.trainingR2.setObjectName("trainingR2")

        self.testingR2 = QtWidgets.QLabel(self.centralwidget)
        self.testingR2.setGeometry(QtCore.QRect(80, 430, 241, 21))
        self.testingR2.setObjectName("testingR2")

        self.runStatus = QtWidgets.QLabel(self.centralwidget)
        self.runStatus.setGeometry(QtCore.QRect(110, 340, 181, 21))
        self.runStatus.setObjectName("runStatus")

        self.waterCHX = QtWidgets.QCheckBox(self.centralwidget)
        self.waterCHX.setGeometry(QtCore.QRect(70, 190, 151, 21))
        self.waterCHX.setObjectName("waterCHX")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 121, 16))
        self.label_3.setObjectName("label_3")
        self.cementCHX = QtWidgets.QCheckBox(self.centralwidget)
        self.cementCHX.setGeometry(QtCore.QRect(70, 210, 151, 21))
        self.cementCHX.setObjectName("cementCHX")

        self.fineaggCHX = QtWidgets.QCheckBox(self.centralwidget)
        self.fineaggCHX.setGeometry(QtCore.QRect(70, 230, 151, 21))
        self.fineaggCHX.setObjectName("fineaggCHX")

        self.finenessmodCHX = QtWidgets.QCheckBox(self.centralwidget)
        self.finenessmodCHX.setGeometry(QtCore.QRect(70, 250, 151, 21))
        self.finenessmodCHX.setObjectName("finenessmodCHX")

        self.silicaCHX = QtWidgets.QCheckBox(self.centralwidget)
        self.silicaCHX.setGeometry(QtCore.QRect(70, 270, 151, 21))
        self.silicaCHX.setObjectName("silicaCHX")

        self.superplasticizerCHX = QtWidgets.QCheckBox(self.centralwidget)
        self.superplasticizerCHX.setGeometry(QtCore.QRect(70, 290, 151, 21))
        self.superplasticizerCHX.setObjectName("superplasticizerCHX")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 490, 81, 16))
        self.label_4.setObjectName("label_4")

        self.compstrength = QtWidgets.QLabel(self.centralwidget)
        self.compstrength.setGeometry(QtCore.QRect(80, 510, 181, 16))
        self.compstrength.setObjectName("compstrength")

        self.slump = QtWidgets.QLabel(self.centralwidget)
        self.slump.setGeometry(QtCore.QRect(80, 530, 131, 16))
        self.slump.setObjectName("slump")

        self.waterplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.waterplainTextEdit.setGeometry(QtCore.QRect(240, 190, 91, 21))
        self.waterplainTextEdit.setObjectName("waterplainTextEdit")
        self.waterplainTextEdit.setPlaceholderText("Water")

        self.cementplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cementplainTextEdit.setGeometry(QtCore.QRect(240, 210, 91, 21))
        self.cementplainTextEdit.setObjectName("cementplainTextEdit")
        self.cementplainTextEdit.setPlaceholderText("Cement")

        self.fineaggplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.fineaggplainTextEdit.setGeometry(QtCore.QRect(240, 230, 91, 21))
        self.fineaggplainTextEdit.setObjectName("fineaggplainTextEdit")
        self.fineaggplainTextEdit.setPlaceholderText("Fine Aggr")

        self.finenessmodplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.finenessmodplainTextEdit.setGeometry(QtCore.QRect(240, 250, 91, 21))
        self.finenessmodplainTextEdit.setObjectName("finenessmodplainTextEdit")
        self.finenessmodplainTextEdit.setPlaceholderText("Fineness mod")

        self.silicaplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.silicaplainTextEdit.setGeometry(QtCore.QRect(240, 270, 91, 21))
        self.silicaplainTextEdit.setObjectName("silicaplainTextEdit")
        self.silicaplainTextEdit.setPlaceholderText("Silica")

        self.superplasticizerplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.superplasticizerplainTextEdit.setGeometry(QtCore.QRect(240, 290, 91, 21))
        self.superplasticizerplainTextEdit.setObjectName("superplasticizerplainTextEdit")
        self.superplasticizerplainTextEdit.setPlaceholderText("Superplasticizer")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 361, 41))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ENGR 499 ML Interface"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Run Model"))
        self.label_2.setText(_translate("MainWindow", "Predict Model"))
        self.predictButton.setText(_translate("MainWindow", "Predict"))
        self.trainingR2.setText(_translate("MainWindow", "Training R<sup>2</sup> Score: "))
        self.testingR2.setText(_translate("MainWindow", "Testing R<sup>2</sup> Score: "))
        self.runStatus.setText(_translate("MainWindow", "Status:"))
        self.waterCHX.setText(_translate("MainWindow", "Water"))
        self.label_3.setText(_translate("MainWindow", "Select Inputs"))
        self.cementCHX.setText(_translate("MainWindow", "Cement"))
        self.fineaggCHX.setText(_translate("MainWindow", "Natural Sand"))
        self.finenessmodCHX.setText(_translate("MainWindow", "FM of Natural Sand"))
        self.silicaCHX.setText(_translate("MainWindow", "Silica Fume"))
        self.superplasticizerCHX.setText(_translate("MainWindow", "Superplasticizer"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Predictions: </span></p></body></html>"))
        self.compstrength.setText(_translate("MainWindow", "Compressive Strength: "))
        self.slump.setText(_translate("MainWindow", "Slump: "))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; text-decoration: underline;\">ENGR 499 Machine Learning Interface</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
